cc_library(
    name = "queues",
    hdrs = [
        "atomicops.h",
        "readerwriterqueue.h"
    ],
    visibility = [
        "//keebird/src:__pkg__"
    ]
)

cc_library(
    name = "log",
    hdrs = [
        "log.h",
    ],
    visibility = [
        "//keebird/src:__pkg__",
        "//keebird/src/ui:__pkg__"
    ]
)
