load("//tools/scripts:openocd.bzl", "openocd_flash")

openocd_flash(
    name = "breakout_flash",
    artifact = "//clock:clock_flash_artifact",
    target = "/usr/share/openocd/scripts/target/stm32l1.cfg"
)

