cc_library(
    name = "ui",
    hdrs = [
        "ui.h",
        "x11_display.h"
    ],
    srcs = [
        "ui.cc",
        "x11_display.cc"
    ],
    visibility = [
        "//keebird/src:__pkg__"
    ],
    linkopts = [
        "-lX11"
    ]
)
