
cc_library(
    name = "synth",
    hdrs = [
        "adsr_envelope.h",
        "note.h",
        "mixer.h",
        "osc.h",
        "voice.h",
        "voice_group.h",
    ],
    srcs = [
        "adsr_envelope.cc",
        "note.cc",
        "osc.cc",
        "voice.cc",
        "voice_group.cc"
    ],
    visibility = [
        "//keebird/src:__pkg__",
        "//keebird/src/ui:__pkg__"
    ]
)
